name: CICD build - test - deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Creating docker
      run: |
       docker build -t api .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Testing with Docker Compose
        run: docker compose run api python -m unittest discover app/tests
          
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger deploy on Render
        run: curl -X POST https://api.render.com/deploy/srv-d0qh086mcj7s73e1he5g?key=LbloELl-Lrg
