name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t api .
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image
      - name: Run docker image
        run: |
          docker-compose run app-teste.py
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger deploy on Render
        run: curl -X POST https://api.render.com/deploy/srv-d0qh086mcj7s73e1he5g?key=LbloELl-Lrg
