name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t api .
      - name: Saving docker
        run: docker save api -o api.tar
      - name: upload docker
        uses: actions/checkout@v4
        with:
          name: api
          path: api.tar
 
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: download docker image
        uses: actions/checkout@v4
        with: 
          name: api
      - name: load
        run: |
          docker load -i api
      - name: run teste
        run:
          docker run api python app-teste.py
      
          
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Trigger deploy on Render
        run: curl -X POST https://api.render.com/deploy/srv-d0qh086mcj7s73e1he5g?key=LbloELl-Lrg
